# A service in Compose is a running container, and service definitions specify information about how each container will run.
version: '3.8'

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:v1.0
    restart: always
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    depends_on:
    - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:v1.0
    restart: always
    env_file: .env
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-network

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:v1.0
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-network

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/mfouadi/Desktop/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/mfouadi/Desktop/data/mariadb'

networks:
  inception-network:
    driver: bridge